package stargatetech2.api.stargate;

public enum DialError{
	// Dialing Errors
	SOURCE_ADDRESS_NOT_FOUND,
	TARGET_ADDRESS_NOT_FOUND,
	SOURCE_WORLD_NOT_FOUND,
	TARGET_WORLD_NOT_FOUND,
	CANNOT_DIAL_SAME_WORLD,
	FAILED_CHUNKLOADING_SOURCE,
	FAILED_CHUNKLOADING_TARGET,
	SOURCE_GATE_NOT_FOUND,
	TARGET_GATE_NOT_FOUND,
	NOT_ENOUGH_POWER,
	TARGET_GATE_BUSY,
	SOURCE_GATE_BUSY,
	
	// Logic
	DIALING_EVENT_CANCELED,
	SUCCESSFULLY_DIALED,
	UNKNOWN_LOGIC_ERROR;
}
