package li.cil.oc.api.event;

import li.cil.oc.api.internal.Agent;
import net.minecraftforge.fml.common.eventhandler.Event;

/**
 * Base class for events generated by robots.
 */
public abstract class RobotEvent extends Event {
    /**
     * The robot for which this event was fired.
     */
    public final Agent agent;

    protected RobotEvent(Agent agent) {
        this.agent = agent;
    }
}
