package li.cil.oc.api.event;

import li.cil.oc.api.machine.Robot;
import net.minecraftforge.event.Event;

/**
 * Base class for events generated by robots.
 */
public abstract class RobotEvent extends Event {
    /**
     * The robot for which this event was fired.
     */
    public final Robot robot;

    protected RobotEvent(Robot robot) {
        this.robot = robot;
    }
}
